#!/bin/sh

set -ex

ORIGDIR=`pwd`
cd `dirname $0` 
DIR=`pwd`
DISTFILES="$DIR"/distfiles

TAG=$1
CACHEDIR=~/.cfe
CLONE="${CACHEDIR}/core.git"

if [ ! -d "${CACHEDIR}"/distfiles ]; then
    mkdir -p "${CACHEDIR}"/distfiles
fi

cd "${CACHEDIR}"/distfiles

xargs -L1 fetch -m <"${DISTFILES}"

cd "$CACHEDIR"
if [ ! -d "${CLONE}" ]; then
    git clone --mirror https://github.com/cfengine/core.git
fi

cd "${CLONE}" 
git remote update 

SOURCES=`mktemp -d`
cd "${SOURCES}"
for ARCHIVE in "${CACHEDIR}"/distfiles/*; do
	tar -xf $ARCHIVE
done

sudo rm -rf /var/cfengine
sudo mkdir -p /var/cfengine

cd tokyocabinet*
./configure --prefix=/var/cfengine
gmake
sudo gmake install
cd ../pcre*
./configure --prefix=/var/cfengine
gmake
sudo gmake install
cd ../libxml*
./configure --prefix=/var/cfengine
gmake
sudo gmake install
cd ../mysql*
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/var/cfengine .
gmake
sudo gmake install

CHECKOUT=`mktemp -d`
git clone "${CLONE}" "$CHECKOUT"
cd $CHECKOUT
if [ ! -z "$TAG" ]; then
	git checkout $TAG
fi
NO_CONFIGURE=YES ./autogen.sh
LDCONFIG="-L/var/cfengine/lib" CFLAGS="-I/var/cfengine/include/" CPPFLAGS="-I/var/cfengine/include/" ./configure --prefix=/var/cfengine -with-libxml2=/var/cfengine --with-tokyocabinet=/var/cfengine --with-pcre=/var/cfengine --with-mysql=/var/cfengine
gmake
sudo gmake install
rm -rf "$CHECKOUT"
rm -rf "$SOURCES"
OVERLAYNAME="cfengine_overlay_head.tgz"
if [ ! -z "$TAG" ]; then 
    : OVERLAYNAME=cfengine_overlay_"${TAG}".tar.gz
fi
cd /
sudo tar -czf "$ORIGDIR"/"$OVERLAYNAME" /var/cfengine

