#!/bin/sh
set -e
cd `dirname $0`
ezjail_jaildir=/usr/jails
. /usr/local/etc/ezjail.conf
if [ ! -d ${ezjail_jaildir}/flavours/buildcfe ]; then
    sudo cp -a ezjail_flavour/buildcfe ${ezjail_jaildir}/flavours/buildcfe
fi

	
